# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gridSplitter_dialog_base.ui'
#
# Created: Fri Mar 27 18:55:24 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_gridSplicerDialogBase(object):
    def setupUi(self, gridSplicerDialogBase):
        gridSplicerDialogBase.setObjectName(_fromUtf8("gridSplicerDialogBase"))
        gridSplicerDialogBase.resize(574, 562)
        self.button_box = QtGui.QDialogButtonBox(gridSplicerDialogBase)
        self.button_box.setGeometry(QtCore.QRect(210, 490, 341, 32))
        self.button_box.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.tabWidget = QtGui.QTabWidget(gridSplicerDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 571, 481))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 20, 551, 391))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 1)
        self.cmdBrowseOutput = QtGui.QPushButton(self.layoutWidget)
        self.cmdBrowseOutput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cmdBrowseOutput.setObjectName(_fromUtf8("cmdBrowseOutput"))
        self.gridLayout.addWidget(self.cmdBrowseOutput, 8, 4, 1, 1)
        self.cmdBrowsetmp = QtGui.QPushButton(self.layoutWidget)
        self.cmdBrowsetmp.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cmdBrowsetmp.setObjectName(_fromUtf8("cmdBrowsetmp"))
        self.gridLayout.addWidget(self.cmdBrowsetmp, 11, 4, 1, 1)
        self.OuptDir = QtGui.QLineEdit(self.layoutWidget)
        self.OuptDir.setObjectName(_fromUtf8("OuptDir"))
        self.gridLayout.addWidget(self.OuptDir, 8, 2, 1, 1)
        self.tempFile = QtGui.QLineEdit(self.layoutWidget)
        self.tempFile.setObjectName(_fromUtf8("tempFile"))
        self.gridLayout.addWidget(self.tempFile, 11, 2, 1, 1)
        self.inputRasterBox = gui.QgsMapLayerComboBox(self.layoutWidget)
        self.inputRasterBox.setFrame(True)
        self.inputRasterBox.setFilters(gui.QgsMapLayerProxyModel.All|gui.QgsMapLayerProxyModel.HasGeometry|gui.QgsMapLayerProxyModel.LineLayer|gui.QgsMapLayerProxyModel.PluginLayer|gui.QgsMapLayerProxyModel.PointLayer|gui.QgsMapLayerProxyModel.PolygonLayer|gui.QgsMapLayerProxyModel.RasterLayer)
        self.inputRasterBox.setObjectName(_fromUtf8("inputRasterBox"))
        self.gridLayout.addWidget(self.inputRasterBox, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 2, 1, 1)
        self.prefixx = QtGui.QLineEdit(self.layoutWidget)
        self.prefixx.setObjectName(_fromUtf8("prefixx"))
        self.gridLayout.addWidget(self.prefixx, 9, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.addTiles = QtGui.QCheckBox(self.layoutWidget)
        self.addTiles.setObjectName(_fromUtf8("addTiles"))
        self.gridLayout.addWidget(self.addTiles, 10, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 6, 2, 1, 1)
        self.splicesXSpinBox = gui.QgsSpinBox(self.layoutWidget)
        self.splicesXSpinBox.setMinimum(1)
        self.splicesXSpinBox.setMaximum(9999)
        self.splicesXSpinBox.setProperty("value", 5)
        self.splicesXSpinBox.setObjectName(_fromUtf8("splicesXSpinBox"))
        self.gridLayout.addWidget(self.splicesXSpinBox, 3, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 5, 2, 1, 1)
        self.tileSizeY = gui.QgsDoubleSpinBox(self.layoutWidget)
        self.tileSizeY.setMinimum(0.0)
        self.tileSizeY.setMaximum(999999999.0)
        self.tileSizeY.setProperty("value", 1.0)
        self.tileSizeY.setObjectName(_fromUtf8("tileSizeY"))
        self.gridLayout.addWidget(self.tileSizeY, 6, 4, 1, 1)
        self.splicesYSpinBox = gui.QgsSpinBox(self.layoutWidget)
        self.splicesYSpinBox.setMinimum(1)
        self.splicesYSpinBox.setMaximum(9999)
        self.splicesYSpinBox.setProperty("value", 5)
        self.splicesYSpinBox.setObjectName(_fromUtf8("splicesYSpinBox"))
        self.gridLayout.addWidget(self.splicesYSpinBox, 4, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 2, 1, 1)
        self.cutLayerBox = gui.QgsMapLayerComboBox(self.layoutWidget)
        self.cutLayerBox.setFilters(gui.QgsMapLayerProxyModel.PolygonLayer)
        self.cutLayerBox.setObjectName(_fromUtf8("cutLayerBox"))
        self.gridLayout.addWidget(self.cutLayerBox, 7, 2, 1, 1)
        self.tileSizeX = gui.QgsDoubleSpinBox(self.layoutWidget)
        self.tileSizeX.setMinimum(0.0)
        self.tileSizeX.setMaximum(999999999.0)
        self.tileSizeX.setProperty("value", 1.0)
        self.tileSizeX.setObjectName(_fromUtf8("tileSizeX"))
        self.gridLayout.addWidget(self.tileSizeX, 5, 4, 1, 1)
        self.numberTilesRadio = QtGui.QRadioButton(self.layoutWidget)
        self.numberTilesRadio.setChecked(True)
        self.numberTilesRadio.setObjectName(_fromUtf8("numberTilesRadio"))
        self.gridLayout.addWidget(self.numberTilesRadio, 3, 1, 1, 1)
        self.tileSizeRadio = QtGui.QRadioButton(self.layoutWidget)
        self.tileSizeRadio.setObjectName(_fromUtf8("tileSizeRadio"))
        self.gridLayout.addWidget(self.tileSizeRadio, 5, 1, 1, 1)
        self.cutLayerRadio = QtGui.QRadioButton(self.layoutWidget)
        self.cutLayerRadio.setObjectName(_fromUtf8("cutLayerRadio"))
        self.gridLayout.addWidget(self.cutLayerRadio, 7, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 430, 501, 20))
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(1, 14, 541, 411))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout.addWidget(self.label_17)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(gridSplicerDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), gridSplicerDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), gridSplicerDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(gridSplicerDialogBase)
        gridSplicerDialogBase.setTabOrder(self.inputRasterBox, self.numberTilesRadio)
        gridSplicerDialogBase.setTabOrder(self.numberTilesRadio, self.splicesXSpinBox)
        gridSplicerDialogBase.setTabOrder(self.splicesXSpinBox, self.splicesYSpinBox)
        gridSplicerDialogBase.setTabOrder(self.splicesYSpinBox, self.tileSizeRadio)
        gridSplicerDialogBase.setTabOrder(self.tileSizeRadio, self.tileSizeX)
        gridSplicerDialogBase.setTabOrder(self.tileSizeX, self.tileSizeY)
        gridSplicerDialogBase.setTabOrder(self.tileSizeY, self.cutLayerRadio)
        gridSplicerDialogBase.setTabOrder(self.cutLayerRadio, self.cutLayerBox)
        gridSplicerDialogBase.setTabOrder(self.cutLayerBox, self.OuptDir)
        gridSplicerDialogBase.setTabOrder(self.OuptDir, self.cmdBrowseOutput)
        gridSplicerDialogBase.setTabOrder(self.cmdBrowseOutput, self.prefixx)
        gridSplicerDialogBase.setTabOrder(self.prefixx, self.addTiles)
        gridSplicerDialogBase.setTabOrder(self.addTiles, self.tempFile)
        gridSplicerDialogBase.setTabOrder(self.tempFile, self.cmdBrowsetmp)
        gridSplicerDialogBase.setTabOrder(self.cmdBrowsetmp, self.tabWidget)
        gridSplicerDialogBase.setTabOrder(self.tabWidget, self.button_box)

    def retranslateUi(self, gridSplicerDialogBase):
        gridSplicerDialogBase.setWindowTitle(_translate("gridSplicerDialogBase", "Grid Splitter", None))
        self.label_6.setText(_translate("gridSplicerDialogBase", "Output Base Directory", None))
        self.label_3.setText(_translate("gridSplicerDialogBase", "Input Layer:", None))
        self.label_7.setText(_translate("gridSplicerDialogBase", "temporary file", None))
        self.cmdBrowseOutput.setText(_translate("gridSplicerDialogBase", "Browse", None))
        self.cmdBrowsetmp.setText(_translate("gridSplicerDialogBase", "Browse", None))
        self.tempFile.setText(_translate("gridSplicerDialogBase", "/tmp/tempshape.shp", None))
        self.label_4.setText(_translate("gridSplicerDialogBase", "number of tiles (X axis)", None))
        self.label_8.setText(_translate("gridSplicerDialogBase", "prefix for output files:", None))
        self.addTiles.setText(_translate("gridSplicerDialogBase", "Add tiles to canvas", None))
        self.label_15.setText(_translate("gridSplicerDialogBase", "tile size (Y axis)", None))
        self.label_14.setText(_translate("gridSplicerDialogBase", "tile size (X axis)", None))
        self.label_5.setText(_translate("gridSplicerDialogBase", "number of tiles (Y axis)", None))
        self.numberTilesRadio.setText(_translate("gridSplicerDialogBase", "number of tiles", None))
        self.tileSizeRadio.setText(_translate("gridSplicerDialogBase", "tile size", None))
        self.cutLayerRadio.setText(_translate("gridSplicerDialogBase", "cut layer", None))
        self.label_18.setText(_translate("gridSplicerDialogBase", "Method:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("gridSplicerDialogBase", "Parameters", None))
        self.label_2.setText(_translate("gridSplicerDialogBase", "Version 0.3. Please report errors to http://hub.qgis.org/projects/gridsplitter", None))
        self.label.setText(_translate("gridSplicerDialogBase", "gridSplitter cuts your input layer into tilesX * tilesY pieces.\n"
"If it is a raster, it tries to keep the raster\'s resolution to avoid gaps and overlaps.\n"
"If the number of splices and the resolution don\'t match up, it cuts slightly larger tiles, resulting in the last tile having a bit of \"no Data\".\n"
"The output is stored in subdirectories in TIF file format.\n"
"Vector layers will be stored in shapefile format.", None))
        self.label_9.setText(_translate("gridSplicerDialogBase", "Input Layer: The Layer you want to process\n"
"", None))
        self.label_10.setText(_translate("gridSplicerDialogBase", "Number of tiles: Specify number of equal tiles you want to create", None))
        self.label_16.setText(_translate("gridSplicerDialogBase", "Tile size: Specify how big the individual tiles will be in map units. They will be snapped to raster resolution", None))
        self.label_17.setText(_translate("gridSplicerDialogBase", "Cut Layer: A polygon layer containing input features. There will be a tile cut for each input feature.", None))
        self.label_11.setText(_translate("gridSplicerDialogBase", "Output Base Directory: Where you want your output to be stored. gridSplitter will make subdirectories for each tile", None))
        self.label_12.setText(_translate("gridSplicerDialogBase", "Prefix for output files (optional): To give the ouput files a better name than [tileX]_[tiley]", None))
        self.label_13.setText(_translate("gridSplicerDialogBase", "Temporary file: a non-existing file to store temporary informations, as some algorithm doesn\'t seem to accept memory layers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("gridSplicerDialogBase", "Info", None))

from qgis import gui
